CSI = '\033['

#colors taken from colorama
BLACK           = f"{CSI}30m"
RED             = f"{CSI}31m"
GREEN           = f"{CSI}32m"
YELLOW          = f"{CSI}33m"
BLUE            = f"{CSI}34m"
MAGENTA         = f"{CSI}35m"
CYAN            = f"{CSI}36m"
WHITE           = f"{CSI}37m"
RESET           = f"{CSI}39m"
LIGHTBLACK_EX   = f"{CSI}90m"
LIGHTRED_EX     = f"{CSI}91m"
LIGHTGREEN_EX   = f"{CSI}92m"
LIGHTYELLOW_EX  = f"{CSI}93m"
LIGHTBLUE_EX    = f"{CSI}94m"
LIGHTMAGENTA_EX = f"{CSI}95m"
LIGHTCYAN_EX    = f"{CSI}96m"
LIGHTWHITE_EX   = f"{CSI}97m"